### ISSUE TITLE
Implement plugin for each platform

### ISSUE THREAD

**Issue by TozyF** [GrassMC/mcdev-gradle-plugin#12]
```[tasklist]
### Tasks
- [x] Add maven central repo as default
- [x] Add sonatype oss repository as default for spigot vendor
- [x] Notice about the applying of a plugin that differs from the platform to the platform vendor
```

**Comment by TozyF** [comment]
Use `spigot-api` legacy version lead missing dependency repositories.

Error message:
```
Could not find net.md-5:bungeecord-chat:1.13-SNAPSHOT.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/net/md-5/bungeecord-chat/1.13-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/net/md-5/bungeecord-chat/1.13-SNAPSHOT/bungeecord-chat-1.13-SNAPSHOT.pom
  - https://hub.spigotmc.org/nexus/content/repositories/snapshots/net/md-5/bungeecord-chat/1.13-SNAPSHOT/maven-metadata.xml
  - https://hub.spigotmc.org/nexus/content/repositories/snapshots/net/md-5/bungeecord-chat/1.13-SNAPSHOT/bungeecord-chat-1.13-SNAPSHOT.pom
Required by:
    project : > org.spigotmc:spigot-api:1.13.2-R0.1-SNAPSHOT:20190423.030901-214
```

**Comment by TozyF** [comment]
Need a message for manual set api vendor.

Recommend use plugin for each platform.
