### ISSUE TITLE
Improve plugin meta validator

### ISSUE THREAD

**Issue by TozyF** [GrassMC/mcdev-gradle-plugin#48]
Add more plugin meta validations.

```[tasklist]
### Validations
- [x] Spigot: name check for `provides`, `depend`, `soft-depend`, `load-before` properties.
- [x] Spigot: main class check for invalid namespace.
- [x] Spigot: check for valid dependency coord in `libraries` property.
- [x] Velocity: id check for dependency id.
- [x] Paper: `main`, `bootstrapper`, `loader` namespace check.
- [x] Paper: `dependencies`, `load-before`, `load-after` name check.
- [x] Paper: `api-version` check.
```
